name: 'API: Pull Request(master)'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Api dependencies
        run: |
          npm install

      - name: Build API Repo
        run: |
          npm run build 

      - name: Run test on API
        run: |
          npm run test
